### ISSUE TITLE
使用上的问题

### ISSUE THREAD

**Issue by tvvbbb** [baoyongzhang/ParcelableGenerator#23]
`@Parcelable
class A{}`
如果是
`List<A> a = new ArrayList<>();
PG.convertParcelable()`

`intent.getParcelable()`
得到的是null来的，必须要把这个list<A>放到一个对象立面才能传递，这个能不能解决？

**Comment by zouzhenglu** [comment]
推荐使用as 的插件， 直接生成parcelable后的代码

**Comment by tvvbbb** [comment]
请问是什么插件？

**Comment by zouzhenglu** [comment]
搜下parcelable就可以了

**Comment by tvvbbb** [comment]
在插件立面么？

**Comment by zouzhenglu** [comment]
对

**Comment by tvvbbb** [comment]
非常多谢你的回答。
